### PR TITLE
added products and filter

### PR DESCRIPTION
**Pull request by omkarpatke**
added multiple items and filter.

### CODE REVIEW

**Review by kgajriaAgarwal — CHANGES_REQUESTED** [review]
The product listing page seems to be good.Kindly try to make it responsive

**Comment by yaswanthmyneni** [comment]
For radio inputs, all three are selected. If you want to select all you can use the checkbox. Also, add a wishlist navigation icon in the 
Screenshot 2022-02-13 at 4 56 24 PM
navbar. The code looks good to me. Can be merged.
Screenshot 2022-02-13 at 4 51 59 PM

**Comment by omkarpatke** [comment]
> For radio inputs, all three are selected. If you want to select all you can use the checkbox. Also, add a wishlist navigation icon in the Screenshot 2022-02-13 at 4 56 24 PM navbar. The code looks good to me. Can be merged. Screenshot 2022-02-13 at 4 51 59 PM

hey, thanks for the suggestion will work on that can you approve the PR.

**Comment by omkarpatke** [comment]
> The product listing page seems to be good.Kindly try to make it responsive

ok, but I think responsive is not mandatory.

**Comment by Sahil25061999** [comment]
Looks good to me, can be merged.

**Review by yaswanthmyneni — APPROVED** [review]
looks good, you can merge.

**Pull request merged**
